### ISSUE TITLE
`jax.tree_leaves` is deprecated

### ISSUE THREAD

**Issue by lucagrementieri** [brentyi/jax_dataclasses#4]
The file `jax_dataclasses/_copy_and_mutate.py` raises many warnings complaining a deprecated function.
```
FutureWarning: jax.tree_leaves is deprecated, and will be removed in a future release. Use jax.tree_util.tree_leaves instead.
```

**Comment by brentyi** [comment]
Thanks! Should be fixed in the latest release; let me know if you're still having issues. :slightly_smiling_face:
